name: Demo deploy ReactJS App to S3

run-name: ${{ github.actor }} is deploying ReactJs App to S3 🚀

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  AWS_S3_BUCKET: reactjs-122022

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
            aws s3 rm --recursive --region ${{ env.AWS_REGION }} s3://${{ env.AWS_S3_BUCKET }}
            aws s3 cp --recursive --region ${{ env.AWS_REGION }} s3://${{ env.AWS_S3_BUCKET }}

      -name: Summary
        run: echo "This job is now running on a ${{ runner.os }}"
        run: echo "Your branch is ${{ github.repository }} / ${{ github.ref }}"
        run: echo "🍏 This job's status is ${{ job.status }}."